### ISSUE TITLE
Fix Form ASM Interaction

### ISSUE THREAD

**Issue by BluRosie** [BluRosie/cfru-edits#2]
Custom form change done by like daniilS is causing problems.
Currently grants Pokérus to the Pokémon changing form.  How is it interacting with the structure?  What needs to be updated?

**Comment by BluRosie** [comment]
looks like nothing needs to be done;  daniilS system just needs to be removed?

**Comment by pkmnrose** [comment]
After reviewing the script

**Comment by pkmnrose** [comment]
After reviewing the script used to test form changes, it was determined that the decrypting and re-encrypting ASM that was used in the original build of the game was causing the checksum/pokerus issue with pokemon.  Since the CFRU disabled encryption, these are no longer needed for scripts.
