### ISSUE TITLE
Overworld palette glitching

### ISSUE THREAD

**Issue by pkmnrose** [BluRosie/cfru-edits#4]
In some screen transitions involving a fadescreen, it appears all OW sprites' palettes are blanked until a screen transition refreshes them.  This has been tested on earlier builds of the rom pre-CFRU, and the issue is not present--further investigation needed.

**Comment by BluRosie** [comment]
looking into restoring the rom to its vanilla handling before applying the cfru to see if that fixes it

**Comment by pkmnrose** [comment]
After removing the Navenatox patch and recompiling CFRU, the palette issues that were experienced before appear to be gone.  Rarely, there is a slight quirk when exiting a map that causes all OWs on the map to have a blanked (#000000 black) palette that's only noticeable for a split-second, but it's still something I've noticed in testing with the new rom.  Unless this turns out to be a larger deal, I will consider this issue closed for now.
